### ISSUE TITLE
support "start at"

### ISSUE THREAD

**Issue by grambas** [KaneCohen/embed#11]
Can you give us some tips to get video  embeds from youtube with start time options
For example link: ...&t=24m10s

**Comment by KaneCohen** [comment]
I'll look into adding that.

**Comment by grambas** [comment]
kind hard coded it today, you can look it at pull request

**Comment by KaneCohen** [comment]
You can of course make a PR. However this should really be implemented in the config file that handles URL parsing and generation.

**Comment by KaneCohen** [comment]
Added YouTube timestamps in latest version of the package - 5.3 and 4.3.2.
