### ISSUE TITLE
Fatal error after generating config cache through artisan on Laravel 5.3

### ISSUE THREAD

**Issue by Jelenik** [KaneCohen/embed#12]
First many thanks for your package and your work. 
I was trying to create config cache through **php artisan config:cache** however it seems that config file from your package is creating fatal error in that cached config file.

`Fatal error: Call to undefined method Closure::__set_state() in xxx\bootstrap\cache\config.php on line 927`

It seems that dataCallback are causing this. Here is code around line 927 ( and there is also one more occurence later ):
```
        'data' => NULL,
        'dataCallback' => 
        Closure::__set_state(array(
        )),
```

Is it possible to fix this somehow ?

**Comment by KaneCohen** [comment]
You can open embed config file in you /config/ folder, find all `dataCallback` keys and set them to null.

**Comment by Jelenik** [comment]
Thank you, it works.
