### ISSUE TITLE
How to use responsive?

### ISSUE THREAD

**Issue by sandervanhooft** [KaneCohen/embed#15]
Hi @KaneCohen ,

Thanks for creating this package.

Do you have some pointers on how to use this responsively instead of with a fixed width and height?

\- Sander

**Comment by KaneCohen** [comment]
Hi Sander. Glad the package is of use. 

I think only way to make embed elements such as IFRAME be responsive is to use JavaScript. 

You can check npmjs.org for packages which provide that functionality.

For example something like this:

<https://www.npmjs.com/package/iframe-resizer>

**Comment by sandervanhooft** [comment]
@KaneCohen I'll look into that, thanks!

**Comment by sandervanhooft** [comment]
Hi @KaneCohen,

The suggested `iframe-resizer` package needs to place a script inside the contained page as well... So that's no use :/.

```
The second file (iframeResizer.contentWindow.min.js) is a native JavaScript file that needs placing in the page contained within your iFrame. This file is designed to be a guest on someone else's system, so has no dependencies and won't do anything until it's activated by a message from the containing page.
```

**Comment by sandervanhooft** [comment]
I fixed it using Bootstrap 3's responsive embed helper:
```
<div class="embed-responsive embed-responsive-16by9">
{!! Embed here... !!}
</div>
```

**Comment by KaneCohen** [comment]
Ok, sounds like a good solution.
