### ISSUE TITLE
Error when trying to load youtube embeded video : Illuminate\Support\ServiceProvider::mergeConfigFrom()

### ISSUE THREAD

**Issue by btechgroup** [KaneCohen/embed#16]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required '/vendor/cohensive/embed/src/Cohensive/Embed/../../config/config.php' (include_path='.:/usr/share/php')

**Comment by KaneCohen** [comment]
What version of Embed do you use? Also what version of Laravel (I'm assuming you use it there)?

**Comment by btechgroup** [comment]
I am using Laravel 5.6 and Embed 5.3

**Comment by KaneCohen** [comment]
OK, Thanks.

**Comment by btechgroup** [comment]
PHP / Ubuntu

PHP Version 7.2.3-1+ubuntu16.04.1+deb.sury.org+1
--

**Comment by KaneCohen** [comment]
Try updating Embed to 5.4 version. I'll look into the issue later today.

**Comment by btechgroup** [comment]
Updating it to 5.4 fixed the issue

**Comment by KaneCohen** [comment]
Alright. Glad to hear that.
