### ISSUE TITLE
Closures in config file

### ISSUE THREAD

**Issue by blong14** [KaneCohen/embed#17]
Hello

I am trying to run `php artisan config:cache` but am triggering an error `Call to undefined method Closure::__set_state()`. It seems that Laravel does not support closures in config files. See below for reference.

https://github.com/laravel/framework/issues/9625

I'm wondering if there is a work around for this or an update can be applied to provide the data for the dataCallback (ie in the youtube config)? I am willing to issue a pull request with an update with a little direction for a clean solution.

**Comment by KaneCohen** [comment]
Thanks for the report.

I have an idea for a workaround - store `Class@action` string which would be executed when necessary. If you have something in mind, you can write your idea here or submit a PR - either way is appreciated.

**Comment by KaneCohen** [comment]
Issue has been fixed for Laravel 5+ in `v5.5.0`.
