### ISSUE TITLE
Class 'Embed' not found (View: C:\wamp64\www\school\resources\views\back\videos\display.blade.php)

### ISSUE THREAD

**Issue by mrhili** [KaneCohen/embed#18]
Laravel 5.5 i followed everything you documented

**Comment by KaneCohen** [comment]
Are you sure you did add `'Embed' => 'Cohensive\Embed\Facades\Embed'` to the app.php aliases?

**Comment by KaneCohen** [comment]
Which version of the library are you using?

**Comment by mrhili** [comment]
it has a direct class i can use ft it dont work as facade ? like Cohensive\Embed::make() or something

**Comment by KaneCohen** [comment]
Yes, the original class is `Cohensive\Embed\Embed`.

https://github.com/KaneCohen/embed/blob/master/src/Cohensive/Embed/Embed.php

However, you'll have to manually set embed configs array as third argument when creating new Embed instance.

**Comment by mrhili** [comment]
so in the second argument what i should put : can you drop an example here?

**Comment by KaneCohen** [comment]
Here's what Facade runs:

```php
        $embed = new Embed($url, $options, $this->config);
        $embed->setProviders($this->providers);
        return $embed;
```

Second and third arguments could be dropped, however you have to inject providers config via:
```php
        $embed->setProviders(config('embed.providers'));
```

**Comment by KaneCohen** [comment]
I really would recommend sorting out issue with why your setup is not seeing the Embed class instead of constructing instance yourself.

**Comment by mrhili** [comment]
Maybe it is the cach or something ?

**Comment by KaneCohen** [comment]
Try clearing cache via `composer dump-autoload`

**Comment by mrhili** [comment]
ok i will

**Comment by mrhili** [comment]
> Which version of the library are you using?

v5.5.0

**Comment by mrhili** [comment]
Still dont work 

{!!  Embed::make($video->url)->parseUrl()->setAttribute([
                                                                    'width' => '100%',
                                                                    'height' => 315,
                                                                    'frameborder' => 0,
                                                                    'allowfullscreen' => true
                                                                    ])->getHtml()  !!}

inthe config part ---------------------------------
--PROVIDERS PART-
        'Cohensive\Embed\EmbedServiceProvider',
--ALIAS PART-
        'Embed' => 'Cohensive\Embed\Facades\Embed'

**Comment by KaneCohen** [comment]
Weird. Try also running:

php artisan cache:clear 
php artisan config:clear

**Comment by mrhili** [comment]
Brother it works thank you alot
