### ISSUE TITLE
Default image if no link provided

### ISSUE THREAD

**Issue by ronlinet** [KaneCohen/embed#19]
I am using this package for dynamic content feeding and it is doing an excellent job. 
In my case I have many live events which still haven't started and in such case I would like to replace the url with a link to a default image. This would be a nice feature to have. 
Thank you for your time.

**Comment by KaneCohen** [comment]
Could you give some close to real life example? Not sure I'm following your proposal - need extra info.

**Comment by ronlinet** [comment]
Hi @KaneCohen , 
It would about defining some constant default image for pending /  not existing or broken links. 
Here is what I am doing.  
``` 
url = ( isset( $url ) ) ? $url : \Config::get('constants.not_existing_video' )
Embed::make( $url )->parseUrl()
```
The 
`url = ( isset( $url ) ) ? $url : \Config::get('constants.access_denied_video' )` may be handled in `Embed::make` .

**Comment by KaneCohen** [comment]
I see. Thanks for the explanation, but I'm don't think this is a good idea. This functionality has no reason to exist on the Embed library - it's not related to the process of generating and embed. It's entirely up to developer and the application logic to decide what to display if `$url` is not set.
