### ISSUE TITLE
Twitch clips not working

### ISSUE THREAD

**Issue by felixmaxime** [KaneCohen/embed#22]
Youtube, dailymotion, etc. work. 

However, with twitch clips nothing loads. 

For example, I tried this clip out: https://www.twitch.tv/clintstevens/clip/CrispyEndearingCiderBibleThump

which was then converted into: 

`<object type="application/x-shockwave-flash" data="https://twitch.tv/widgets/live_embed_player.swf?channel=clintstevens" wmode="transparent" id="live_embed_player_flash" width="500" height="350"><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><param name="allowNetworking" value="all"></param><param name="flashvars" value="hostname=www.twitch.tv&channel=clintstevens&auto_play=false&start_volume=25"></param><param name="movie" value="https://www.twitch.tv/widgets/live_embed_player.swf"></param></object> `

however, when putting that on my website, it's just blank. 

![Untitled](https://user-images.githubusercontent.com/12413944/67119496-488bb200-f1b5-11e9-861f-c11d4c7de547.png)

**Comment by KaneCohen** [comment]
Added config for twitch. Make sure you use "dev-master" version.

If needed I can port it for older versions.

**Comment by felixmaxime** [comment]
Updated composer with dev.master. Still getting the same problem. Only with twitch.

**Comment by KaneCohen** [comment]
@felixmaxime updated providers config order. Please, run update on the library to fetch latest changes and try again.
