### ISSUE TITLE
Call to undefined method Cohensive\Embed\Embed::make()

### ISSUE THREAD

**Issue by muhragab** [KaneCohen/embed#25]
could you help please 
Call to undefined method Cohensive\Embed\Embed::make()

            {!! \Cohensive\Embed\Embed::make($lessonsInfo->urlContent)->parseUrl($lessonsInfo->urlContent)->setAttribute([
            'width' => '100%',
            'height' => 315,
            'frameborder' => 0,
            'allowfullscreen' => true
            ])->getHtml() !!}

**Comment by KaneCohen** [comment]
@muhragab you need to use `make` on Factory, not on Embed class itself:

```php
\Cohensive\Embed\Factory::make($lessonsInfo->urlContent)...
```
