### ISSUE TITLE
Latest Update broke Plugin for L4.2

### ISSUE THREAD

**Issue by DominikVogt** [KaneCohen/embed#4]
Got an error after your latest update. Would be awesome if you commit a fix :)

{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method Cohensive\\Embed\\EmbedServiceProvider::mergeConfigFrom()","file":"C:\\xampp18\\htdocs\\fotinity-portal\\vendor\\cohensive\\embed\\src\\Cohensive\\Embed\\EmbedServiceProvider.php","line":31}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error

**Comment by KaneCohen** [comment]
You need to update your composer.json file.

Most likely you have something like:

````php
"cohensive/embed": "dev-master"
````

Switch it to

````php
"cohensive/embed": "~4.2.0"
````

**Comment by DominikVogt** [comment]
Yeah we have allready done so. I just wanted to let you know. Maybe you want to fix it in your newest release, to allow backwards compatibility when including new features.

Still a helpfull plugin though :)

Von meinem iPhone gesendet

Am 06.02.2015 um 11:46 schrieb Kane Cohen <notifications@github.com<mailto:notifications@github.com>>:


You need to update your composer.json file.

Most likely you have something like:

"cohensive/embed": "dev-master"

Switch it to

"cohensive/embed": "~4.2.0"

**Comment by KaneCohen** [comment]
Last update was mostly targeted at Laravel since L5 has new way to handle configuration loading.

Regarding features - I will be backporting them to 4.x version when possible (those that don't break behavior).

Anyway, thanks for the issue. I've updated readme with details on how to use package with L4 and L5.
