### ISSUE TITLE
Call to undefined method Illuminate\\Foundation\\Application::bindShared()

### ISSUE THREAD

**Issue by greatwitenorth** [KaneCohen/embed#8]
I'm trying to install 4.2.0 on Laravel 4.0.*. It appears as though bindShared() is not a method. Some suggest it was renamed to singleton, although I'm not sure when that happened. Full error:

```
$ php artisan clear-compiled
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method Illuminate\\Foundation\\Application::bindShared()","file":"\/laravel\/vendor\/cohensive\/embed\/src\/Cohensive\/Embed\/EmbedServiceProvider.php","line":22}}
```

**Comment by greatwitenorth** [comment]
possible solution here:
https://github.com/KaneCohen/embed/pull/9

**Comment by KaneCohen** [comment]
Hm, quick question - have you tried using `5.2` version of the package? or it won't work with L 4.0.*?

**Comment by greatwitenorth** [comment]
I have not tried 5.2 with L4. Is it compatible?

**Comment by KaneCohen** [comment]
I've added required change in 4.3.1 version.

**Comment by greatwitenorth** [comment]
great! thanks for the quick fix.
